In [52]:
import pandas as pd
import numpy as np
import sklearn
import pdfplumber as plu

In [53]:
df=pd.read_csv(r"C:\Users\sharr\OneDrive\Desktop\Python\Resume dataset\Project\Complete_data.csv")

In [54]:
df.head()

Tags  \
0  Experienced Networkengineer skilled in Configu...   
1  Experienced Powerengineer skilled in LoadFlow,...   
2  Experienced Telecommunicationengineer skilled ...   
3  Experienced Protectionengineer skilled in Tran...   
4  Experienced Signalprocessingengineer skilled i...   

                    Position  
0            Networkengineer  
1              Powerengineer  
2  Telecommunicationengineer  
3         Protectionengineer  
4   Signalprocessingengineer

In [55]:
# extract the features words 
from sklearn.feature_extraction.text import TfidfVectorizer

vec=TfidfVectorizer(max_features=4000,stop_words='english')

vector=vec.fit_transform(df['Tags']).toarray()

print(vector)


[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.24103191 0.16680611 0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [56]:
from sklearn.metrics.pairwise import cosine_similarity

sim=cosine_similarity(vector)

print(sim)


[[1.         0.13475096 0.22790885 ... 0.02401612 0.02528354 0.02705524]
 [0.13475096 1.         0.15693181 ... 0.025397   0.1174407  0.02861086]
 [0.22790885 0.15693181 1.         ... 0.02473303 0.02603828 0.02786286]
 ...
 [0.02401612 0.025397   0.02473303 ... 1.         0.17310768 0.18523789]
 [0.02528354 0.1174407  0.02603828 ... 0.17310768 1.         0.19501355]
 [0.02705524 0.02861086 0.02786286 ... 0.18523789 0.19501355 1.        ]]


In [57]:
pdf1=plu.open("Resume 1.pdf")
page1=pdf1.pages[0]
text1=page1.extract_text()

par1=text1.replace("\n"," ")

par1
pdf=plu.open('it_resume.pdf')

page=pdf.pages[0]

text=page.extract_text()

par=text.replace("\n"," ")
print(par)

Tushar Wansinge VJTI, Mumbai, Maharashtra (cid:131) 9168787276 # tusharwansinge45@gmail.com #tvwansinge 21@ee.vjti.ac.in b Education VJTI Dec 2021 – current Bachelor of Technology in Electrical Engineering. (CGPA - 8.18) Mumbai Hislop Junior College Nagpur 2019 – 2021 Maharashtra State Board,Pune (HSC Percentage - 93, MHT-CET Percentile - 96.389) Nagpur, Maharashtra Chanda Public School,Chandrapur 2019 Central Board of Secondary Education (SSC Percentage - 89.8) Chandrapur, Maharashtra Relevant Coursework • Electrical Machines • Power Systems • Power Electronics • Electrical Networks • Analog and Digital Circuits • Project Management Personal Projects Power BI Dashboards • Built an interactive Logistics dashboard which shows various insights of parameters related to Key Performance Indicators. • Performed data cleaning in Excel on given data and turned into an interactive dashboard in Power BI. Electrical Vehicle design using MATLAB Software • Simulated a design of Electric Vehicle on 

In [58]:
# n_vec=vec.transform([par]).toarray()
# similarities=cosine_similarity(n_vec,vector)[0]
# df['similarities']=similarities

# n_vec1=vec.transform([par1]).toarray()
# similaritie1=cosine_similarity(n_vec1,vector)[0]
# df['similaritie1']=similaritie1

In [59]:
df.columns

Index(['Tags', 'Position'], dtype='object')

In [60]:
# max_1=df['similarities'].max() 
# df_1=df[df['similarities']== max_1]
# role_1=df_1['Position'].values[0]
# df_new=df[df['Position'] != role_1]

# max_2=df_new['similarities'].max()
# df_2=df[df['similarities']== max_2]
# role_2=df_2['Position'].values[0]

# print(role_1,role_2)

In [61]:
# max_3=df['similaritie1'].max() 
# df_3=df[df['similaritie1']== max_3]
# role_3=df_3['Position'].values[0]
# df_new3=df[df['Position'] != role_3]

# max_4=df_new3['similaritie1'].max()
# df_4=df[df['similaritie1']== max_4]
# role_4=df_4['Position'].values[0]
# df_new4=df[df['Position'] != role_4]


# print(role_3,role_4)

In [62]:
print(par1)
print(par)


YASH MHATRE +91-7020257087 Roll No.: 241030901 mailto:ymmhatre_b23@ee.vjti.ac.in ELECTRICAL ENGINEERING Veermata Jijabai Technological Institute, Mumbai ï Yash Mhatre Education Veermata Jijabai Technological Institute (VJTI) • Bachelor of Technology in Electrical Engineering AUG.2025-CURRENT Veermata Jijabai Technological Institute (VJTI) CGPA: 8.61 • June 2021-May 2024 Diploma in Electrical Engineering Percentage:96.89 • M.G.V HIGHSCHOOL May 2020 SSC,Board Percentage: 91.80 Experience Brihanmumbai Electricity Supply and Transport Undertaking • (JUNE23-JULY23) Industrial Trainee Mumbai – learn about maintenance of underground transmission lines, & fault detection. – Gained knowledge of preventive maintenance and power distribution systems. The Tata Power Company Limited (JUNE25-JULY25) • INTERNSHIP Mumbai – Gained training of the cable department and different types of HT/EHV cables – Learned cable maintenance practices, fault locating, and jointing techniques. Personal Projects Hybrid

In [63]:
# df_new=df[df['Position']=='IoTengineer']
# r1max=df_new['similarities'].max()
# r2max=df_new['similaritie1'].max()
# if r2max >r1max:
#     print("Resume 1 selected")
# else:
#     print("it_resume")

In [64]:
import joblib

# Save vectorizer
joblib.dump(vec, "vectorizer.pkl")

# Save feature matrix
joblib.dump(vector, "feature_matrix.pkl")

# Save dataframe (without reloading CSV later)
joblib.dump(df, "data.pkl")


['data.pkl']

In [65]:
df

Tags  \
0     Experienced Networkengineer skilled in Configu...   
1     Experienced Powerengineer skilled in LoadFlow,...   
2     Experienced Telecommunicationengineer skilled ...   
3     Experienced Protectionengineer skilled in Tran...   
4     Experienced Signalprocessingengineer skilled i...   
...                                                 ...   
3995  Experienced FullStackDeveloper with expertise ...   
3996  Experienced MachineLearningEngineer with exper...   
3997  Experienced VLSIDesignEngineer with expertise ...   
3998  Experienced PowerSystemsEngineer with expertis...   
3999  Experienced BackendDeveloper with expertise in...   

                       Position  
0               Networkengineer  
1                 Powerengineer  
2     Telecommunicationengineer  
3            Protectionengineer  
4      Signalprocessingengineer  
...                         ...  
3995         FullStackDeveloper  
3996    MachineLearningEngineer  
3997         VLSIDesignEngineer  
3998       PowerSystemsEngineer  
3999           BackendDeveloper  

[4000 rows x 2 columns]

In [66]:
with plu.open("Resume 1.pdf") as pdf:
    page=pdf.pages[0]
    text=page.extract_text()
    par=text.replace("\n"," ")
print(par)

YASH MHATRE +91-7020257087 Roll No.: 241030901 mailto:ymmhatre_b23@ee.vjti.ac.in ELECTRICAL ENGINEERING Veermata Jijabai Technological Institute, Mumbai ï Yash Mhatre Education Veermata Jijabai Technological Institute (VJTI) • Bachelor of Technology in Electrical Engineering AUG.2025-CURRENT Veermata Jijabai Technological Institute (VJTI) CGPA: 8.61 • June 2021-May 2024 Diploma in Electrical Engineering Percentage:96.89 • M.G.V HIGHSCHOOL May 2020 SSC,Board Percentage: 91.80 Experience Brihanmumbai Electricity Supply and Transport Undertaking • (JUNE23-JULY23) Industrial Trainee Mumbai – learn about maintenance of underground transmission lines, & fault detection. – Gained knowledge of preventive maintenance and power distribution systems. The Tata Power Company Limited (JUNE25-JULY25) • INTERNSHIP Mumbai – Gained training of the cable department and different types of HT/EHV cables – Learned cable maintenance practices, fault locating, and jointing techniques. Personal Projects Hybrid

In [67]:
# recommend positions
def file (file):
    with plu.open(file) as pdf:
        page=pdf.pages[0]
        text=page.extract_text()
        par=text.replace("\n"," ")
    rvec=vec.transform([par]).toarray()
    sim=cosine_similarity(rvec,vector)[0]
    df['sim']=sim
    df_new=df.sort_values(by='sim',ascending=False).iloc[:50]
    lis=df_new['Position'].unique().tolist()
    print(f" 1 {lis[0]} \n 2 {lis[1]} \n 3 {lis[2]}")


In [68]:
file("it_resume.pdf")

 1 Powerengineer 
 2 Dataanalyst 
 3 Data Analyst


In [69]:
# compare the resume
files=["Resume 1.pdf","it_resume.pdf","resume tronics.pdf"]
for file in files:
    with plu.open(file) as pdf:
        page=pdf.pages[0]
        text=page.extract_text()
        par=text.replace("\n"," ")
        print(file)
        rvec=vec.transform([par]).toarray()
        rsim=cosine_similarity(rvec,vector)[0]
        df[f"{file}"]=rsim


Resume 1.pdf
it_resume.pdf
resume tronics.pdf


In [70]:
df.columns

Index(['Tags', 'Position', 'sim', 'Resume 1.pdf', 'it_resume.pdf',
       'resume tronics.pdf'],
      dtype='object')

In [ ]:
# Columns to compare
cols = ['Resume 1.pdf', 'it_resume.pdf', 'resume tronics.pdf']

# Maximum value per row
df['max_similarity'] = df[cols].max(axis=1)

# Column name (resume) with the maximum value per row
df['best_resume'] = df[cols].idxmax(axis=1)

# Show results
df[['max_similarity', 'best_resume']]


In [100]:
# Columns to compare
cols = ['Resume 1.pdf', 'it_resume.pdf', 'resume tronics.pdf']

# Maximum value per row
df['max_similarity'] = df[cols].max(axis=1)

df['best_resume']=df[cols].idxmax(axis=1)

ok=df['best_resume'].value_counts()
on=pd.DataFrame(ok)
print(on.index[0])



it_resume.pdf


In [72]:
df[['Resume 1.pdf', 'it_resume.pdf','resume tronics.pdf']].max(axis=1)

0       0.157187
1       0.130596
2       0.070685
3       0.133354
4       0.080186
          ...   
3995    0.055631
3996    0.084501
3997    0.045482
3998    0.149590
3999    0.066118
Length: 4000, dtype: float64